### ISSUE TITLE
Boolean rules always set to required

### ISSUE THREAD

**Issue by mariopro** [laracraft-tech/laravel-schema-rules#14]
Great package, but I found that the boolean (TINYINT) is always set to `'some_field' => ['required', 'boolean']`, when we know that by default, checkboxes and other boolean fields, if not checked or selected, will not be present in the request payload, therefore the creation of the rules for boolean values should, IMHO, be treated as `['sometimes', 'boolean']`.

**Comment by Sairahcaz** [comment]
I'm gonna close this for now, as I have not the time to work on that, feel free to send a PR if you like!
