### ISSUE TITLE
Unique columns not being set

### ISSUE THREAD

**Issue by mariopro** [laracraft-tech/laravel-schema-rules#15]
I found another issue with unique columns that are not being set as unique in the rules. For instance I have the `guid` column that is set as  unique in the table definitions, and when generating the rules it sets as follows: `'guid' => ['required', 'string', 'min:1', 'max:191']` where it should be `'guid' => ['required', 'string', 'min:1', 'max:191', 'unique:table_name,guid']`
Please note that these are constructive contributions to make the package even better.

**Comment by Sairahcaz** [comment]
That's also a very good idea. Thanks for your feedback, I'll try to implement it the next few days...
