### ISSUE TITLE
Implicit rules instead of scaffolding on the fly

### ISSUE THREAD

**Issue by shaedrich** [laracraft-tech/laravel-schema-rules#16]
It would be nice if I could do something like this:

```php
public rules()
{
    return [
        'email' => 'email:rfc,dns',
    ] + \LaracraftTech\LaravelSchemaRules\Resolvers\BaseSchemaRulesResolver::generate();
}
```

or do you consider this out of scope?

I know, the above code is just pseudocode. There would have to be a `merge()` method to prevent the keys from overwriting each other.

**Comment by Sairahcaz** [comment]
Hi @shaedrich, I don't think this is a good idea, cause the `generate` method is doing some database queries and I don't think you want this overhead on every request...

**Comment by shaedrich** [comment]
Hi @Sairahcaz, I never said, it couldn't be [cached](https://laravel.com/docs/cache) 😉
