### ISSUE TITLE
error generating from mysql table

### ISSUE THREAD

**Issue by theAusMenace** [laracraft-tech/laravel-schema-rules#6]
Thanks for writing this, going to save us all a heap of time.
 
php 8.1.12 Ubuntu
Laravel Framework 10.15.0 
mysql 5.8 (latest up to date)

**to Replicate ...**
php artisan schema:generate-rules quotes

**Error ...**
 ErrorException 

  Undefined array key "int(11)"

  at vendor/laracraft-tech/laravel-schema-rules/src/Resolvers/SchemaRulesResolverMySql.php:93
     89▕             case $type->contains('int'):
     90▕                 $columnRules[] = "integer";
     91▕                 $sign = ($type->contains('unsigned')) ? 'unsigned' : 'signed' ;
     92▕                 $intType = $type->before(' unsigned')->__toString();
  ➜  93▕                 $columnRules[] = "min:".self::$integerTypes[$intType][$sign][0];
     94▕                 $columnRules[] = "max:".self::$integerTypes[$intType][$sign][1];
     95▕ 
     96▕                 break;
     97▕             case $type->contains('double') ||

      +15 vendor frames 
  16  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()

**Table Structure**
Field	Type	Null	Key	Default	Extra
id	int(11)	NO	PRI	NULL	auto_increment
quotename	varchar(255)	YES			
carrid	int(11)	NO		0	
siteid	int(11)	YES		0	
contactid	int(11)	NO		-1	
dateissued	date	NO		NULL	
dateeffective	date	NO		NULL	
dateexpires	date	NO		NULL	
commodity	char(25)	YES		NULL	
hcode	char(30)	YES		NULL	
priority	char(25)	YES		NULL	
lodgepoint	char(20)	YES		NULL	
orig	char(3)	YES		NULL	
remarks	text	YES		NULL	
notes	text	YES		NULL	
final	char(3)	YES		NULL

**Comment by Sairahcaz** [comment]
Did you installed the package only yesterday?

@giagara any ideas? :D

**Comment by theAusMenace** [comment]
> Did you installed the package only yesterday?
> 
> @giagara any ideas? :D

I installed it about an hour before this report - 1st time use so excuse me if I'm not doing it correctly. I followed 

$ composer require laracraft-tech/laravel-schema-rules --dev
$ php artisan vendor:publish --tag="schema-rules-config"

then

$ php artisan schema:generate-rules quotes

**Comment by giagara** [comment]
Mysql 5.8 uses a slightly different syntax like `int(11)` for the integer values. I'm preparing a PR to fix it

**Comment by giagara** [comment]
PR #7 is ready for review.

**Comment by Sairahcaz** [comment]
@giagara thanks for your fix here!

@theAusMenace I released a new version with the fix, feel free to update the package and try again!

**Comment by theAusMenace** [comment]
> @giagara thanks for your fix here!
> 
> @theAusMenace I released a new version with the fix, feel free to update the package and try again!

Works like a charm
I tip my hat to you sir ...
